version: "3.8"

services:
  api:
    build: .
    container_name: ecosync-api
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - JWT_SECRET=changemoi
    volumes:
      - .:/app
    command: npm run dev
